foo:
  simple-prop1: some simple property
boo:
  flag: false
  inner-class-var:
    str-prop: property of inner pojo defined as var property
    duration-prop: 10s
    long-prop: 11
  inner-class-val:
    str-prop: property of inner pojo defined as val property
    duration-prop: 10s
    long-prop: 11
  external-data-class:
    prop1: property of external data class defined as var property
  external-class-with-vals-val:
    prop1: property of external class defined as initialized val property
  external-class-with-vars-var:
    prop1: property of external class defined as var property
bar:
  data:
    bar-data: property of external class defined as constructor parameter
    bar-bar-data: property of external class defined as constructor parameter with initial value
  inner:
    foo-data: property of inner data class defined as constructor parameter
  initialized-prop: some
  another-prop: another
json-only:
  prop: from additional-spring-configuration-metadata.json
my:
  data:
    initialized-prop: foo
    another-initialized-prop: bar
    #not-initialized-prop: not-initialized
